sudo: required
services:
  - docker


before_install:
  - docker build -t therealsheng/docker-react -f Dockerfile.dev .

script:
  - docker run therealsheng/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "Docker_react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-548876645614"
  bucket_path: "Docker_react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"


    